### ISSUE TITLE
indicate elements that have hidden associations

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/aixm-graph#1]
It would be useful to distinguish on the graph between elements that are “final” (in the sense that all their associations are displayed) and elements that still have “hidden associations” (which can be added to the graph by click on the element). This would save unnecessary clicks on the graph. For example, a little “+” symbol after the element name would indicate that there are still hidden associations?

**Comment by antavelos** [comment]
Done.

An expandable feature is indicated with a [+] in front of its label, i.e.: [+] NAV

**Comment by porosnie** [comment]
It works well. I think that we can close the issue.
