### ISSUE TITLE
copy UUID from pop-up label

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/aixm-graph#2]
It would be useful to be able to copy the UUID value of an element from the pop-up label. That would facilitate searching that element in the XML file, if something needs to be verified for the element coding. Something like "Shift+click", if technically possible. It could be acceptable to be browser-specific.

**Comment by antavelos** [comment]
Done.

The UUID of a feature can be copied with Ctrl+c as soon as the popup of its corresponding node is displayed.

**Comment by porosnie** [comment]
I tested it and it works nicely. Good idea. I propose to close the issue, unless there is something more that you want to do with it.
