### ISSUE TITLE
filter associations that are shown

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/aixm-graph#4]
On a file such as 2004_v6, there are features that have many associations. This results in a very cluttered screen, dificult to analyse. 

Would it be possible to implement a checkboxes that would allow to hide certain associations? For example, on the left side of the screen to have the list of all the associations that are shown (based on what is actually in the screen). When de-selecting on or more, the corrsponding association types would be hidden.

See the picture attached.

![image](https://user-images.githubusercontent.com/8693439/77548826-5f92a680-6eaf-11ea-9caa-08672e9b7be1.png)

**Comment by antavelos** [comment]
Yes, that's a good idea. However, adding it on the left side of the graph would be quite tricky to implement so I'd suggest instead to put an extra filter above it (where the rest of the filters exist at the moment) and allow to check/uncheck the available features from a dropdown list.

**Comment by porosnie** [comment]
That's OK. It would also be nice to have a "select/deselect all", as in Excel when you filler records.

**Comment by antavelos** [comment]
Sure!

**Comment by antavelos** [comment]
@porosnie I'd like some clarification regarding the expanded associations:

1. Should we add them in the checkbox list as well?
2. If an association is deselected should we also hide its expanded child associations?

**Comment by porosnie** [comment]
I think that only the first level associations should be listed, not the expanded ones. 
If an association is de-selected, the whole branch (including eventually expanded associations) should be hidden.

**Comment by antavelos** [comment]
@porosnie Done.

Having a filter with checkboxes on the filter area was trickier than I thought (considering some limitation of the used front-end framework) so I put the list on the area of the graph as you proposed.

**Comment by porosnie** [comment]
This looks great. It works well on Donlon, but I would like to test it further. On the EV data set, sometimes I do not get anything on the screen. For example, if I select Navaid, I do not get any results. I will try with other browsers, not Edge.

**Comment by antavelos** [comment]
I'm afraid that when there are a lot of features about to display it takes some time to render them all..
