### ISSUE TITLE
missing associations for root element

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/aixm-graph#5]
Step
- open EA_AIP_... (Donlon)
- select Navaids
- add filter "ILS"
Result:
- ILS, OLX is shown as root, but only with 4 associations (instead of all 7).

Maybe a temporary issue because of the work in progress on the "filter by associated type"?

**Comment by antavelos** [comment]
It seems that the feature NavaidEquipment (missing links) is not configured the list of features thus it's not represented as a graph node. I'll update the list accordingly.

**Comment by antavelos** [comment]
@porosnie please discard my previous comment as invalid.

Checking the specific Navaid in the file I see 5 <aixm:navaidEquipment> entries. One them has xlink towards a specific Localizer and the rest four have xlink towards a specific MarkerBeacon. Both of them are represented on the graph along with two more. So 4 associations are displayed but essentially they are 7.

Should we represent all of them on the graph? If so how could we differentiate among them in a displayable way?

**Comment by porosnie** [comment]
Let me check the file, there might be something wrong in the data

**Comment by porosnie** [comment]
You are right, the Donlon file is incorrect. I will correct the Xlink:href values to naiads. 

As a side notice, with the AIXM-Graph I could identify other 5 errors in the Donlon sample!
