### ISSUE TITLE
Skeleton file - add gml:identifier element

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/aixm-graph#6]
In the Skeleton file, it would be nice to preserve the gml:identifier element.
That's because not all AIXM files will comply with the recommendation to use as gml:Id of the feature the same UUID value as for the gml:identifier. Having the gml:identifier would facilitate searching with an XML editor in the skeleton file in order to understand the meaning of certain associations displayed in the Graph.

**Comment by antavelos** [comment]
@porosnie Done
