### ISSUE TITLE
warning for broken links can be misinterpreted

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/aixm-graph#8]
The current warning for broken links does not indicate how many are. A test user though that the number of feature instances (such as "20" for Airspace in the Donlon file) means that there are 20 broken links. In fact, there is only one.

Is it possible to add the number of broken links after the exclamation mark?

**Comment by antavelos** [comment]
@porosnie I think that adding another number in there would be more confusing. I'd suggest to report the features like `(number of valid features / total number)`. For example Airspace (19/20) which indicates that not all of them were valid. 

We could also add a tooltip that will appear on the features with broken links upon mouse hover saying something like: `Found 1 feature with broken xlinks`.

What do you think?

**Comment by antavelos** [comment]
An alternative approach would be to display no icon by default except for the ones with broken links and then display a tooltip upon mouse hover explaining the the reason of the report. I think that would simplify the UI.

**Comment by porosnie** [comment]
The number of instances with broken links is an interesting information. What if there were two entries in the left side menu, for the same feature? One line for those with broken links, one for those without? Something like below:
![image](https://user-images.githubusercontent.com/8693439/80495218-ed0e5e00-8967-11ea-9c20-f4e1f489bd14.png)

If there are no broken links, only one feature line should be displayed. 

That would also simplify the access to the instances with broken links.

**Comment by antavelos** [comment]
@porosnie to be honest I think having two entries of the same feature is a bit verbose. 

What I propose looks like this:

![proposition](https://user-images.githubusercontent.com/1507101/80502215-a2ddaa80-8970-11ea-89f5-77fb99dd7bf5.png)

**Comment by porosnie** [comment]
OK!

**Comment by antavelos** [comment]
Done.
